### ISSUE TITLE
Message formatting

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#114]
Furthering #110.

This was originally added in #1 for the pre-Riot client. Now that we've gone through about a billion rewrites, we need to implement message formatting again.

**Comment by heyitsmeuralex** [comment]
[mrk](https://github.com/heyitsmeuralex/mrk) has been made for this purpose. Extensions we need:

* [x] Strikethrough
* [ ] Images
* [ ] Channel/server references
* [ ] @mentions

**Comment by heyitsmeuralex** [comment]
Images have been done in #130.

**Comment by heyitsmeuralex** [comment]
Going to defer mentions to #92.

**Comment by heyitsmeuralex** [comment]
![image](https://user-images.githubusercontent.com/9429556/34297315-60be3134-e70f-11e7-8f3a-30a84be1af80.png)
