### ISSUE TITLE
Improve message date formatting

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#116]
#112 implemented a basic timestamp system, showing every message group's date. It displays the full date-time string, though, which is often more than wanted. See #15 for discussion.

**Comment by PullJosh** [comment]
We already have a system for this.

< 60sec: `just now`
60sec - 30 min: `X mins` (or `1 min`)
31min - 24 hours: `X hours` (or `1 hour`) -- rounded, not floored
24+ hours: `X days` (or `1 day`)

Every date should also have title text that allows the entire datetime to be viewed on hover.

**Comment by towerofnix** [comment]
@PullJosh Thanks. I couldn't find that on GitHub anywhere but I knew we had one!

**Comment by heyitsmeuralex** [comment]
This was also done in `riot`, and we can just copy the code from there. See `<message>`.

**Comment by heyitsmeuralex** [comment]
>24+ hours: X days (or 1 day)

Wasn't this `Nov 3` etc? I'd say if:

* 7+ days: `Date` -- e.g. `Dec 6`

**Comment by towerofnix** [comment]
@heyitsmeuralex Yup, updated @PullJosh's post.

**Comment by PullJosh** [comment]
Yes. Thank you.
