### ISSUE TITLE
Client rewrite war!

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#122]
Blocks *literally every other issue.* (Except maybe some backend ones.) Should fix a few.

Here we go...

### What on earth is the client rewrite *war*??????????

This is a *fun, competitive project* in which a bunch of people (well, @PullJosh and @heyitsmeuralex) write clients for Decent. The "best" one is merged into this repository and used as the official one.

### What kinds of clients?

We're looking to make a replacement for the current "official" client program - that's the one that exists within the `towerofnix/decent` repository. This means that the client just one basic condition: **The client should work in your web browser.** Mind you, using recent ES2017/whatever features is okay; just as long as your client works inside a (normal: firefox, chrome, not IE) browser.

### Can I use Browserify?

Yes. Use *Babel*, if you want to - I don't care.

### What does my client need to do?

There's only one *essential* guideline, which I stated above: the client should work in your web browser. You can't replace the existing client with [a plugin for weechat](https://github.com/towerofnix/decent/issues/79), sorry. :)

However, there *is* a list of things your client must be able to do. Remember that *you are writing a replacement,* so your code needs to do everything that the current client does *and some more* (so that there's bonus incentive to use your client, rather than what is currently here).

Furthermore, **your client must be based on @PullJosh's [design](https://codepen.io/PullJosh/pen/OOYZWK).**

Good news for you, [the current client](https://github.com/towerofnix/decent/tree/34288140b32eb10f70f95876fadb4877b3807552/site) is very simple. However, we want more than what's there. Here's a checklist for the features you should support (~~copy/paste it into your PRor whatever - don't click the buttons here~~ progress on alex's PR #126):

- [x] Support selecting a server. The server dropdown should be filled.
- [x] Support viewing channels. The sidebar channel list should automatically be filled when you select a server, and should automatically update according to the [appropriate](https://github.com/towerofnix/decent/wiki/API#from-server-created-new-channel) [websocket](https://github.com/towerofnix/decent/wiki/API#from-server-renamed-channel) [events](https://github.com/towerofnix/decent/wiki/API#from-server-deleted-channel).
- [x] Support registering. **There should be some sort of a modal - do *not* use `prompt`.** Handle error messages appropriately (unfortunately there's no documentation for them, but you can read [the code](https://github.com/towerofnix/decent/blob/34288140b32eb10f70f95876fadb4877b3807552/api.js#L895-L934); it's pretty self descriptive and easy to follow). You should confirm that the entered username [is available](https://github.com/towerofnix/decent/wiki/API#get-apiusername-availableusername) before actually sending [the register request](https://github.com/towerofnix/decent/wiki/API#post-apiregister).
- [x] Support logging in and out. Logging in means making [the appropriate request](https://github.com/towerofnix/decent/wiki/API#post-apilogin) and keeping track of the returned session ID; logging out means discarding that session ID. These should update the "user info" display (username, log in/out/register buttons), obviously.
  - [x] Support handling the [`ping for data`](https://github.com/towerofnix/decent/wiki/API#to-client-ping-for-data) WebSocket event. You can confirm this is working by checking [the user list endpoint](https://github.com/towerofnix/decent/wiki/API#get-apiuser-list): when you're logged in, the user of the session ID you're logged in with should show as "online" there.
- [x] Support sending messages. Pressing enter in the text field should [submit a message](https://github.com/towerofnix/decent/wiki/API#post-apisend-message) (and so should clicking the "send" button).
- Support reading messages.
  - [x] Read messages as they're sent by handling [the relevant WebSocket event](https://github.com/towerofnix/decent/wiki/API#from-server-received-new-message).
  - [x] Fetch the most recent messages. [There's an API for that.](https://github.com/towerofnix/decent/wiki/API#get-apichannelchannelidlatest-messages)
  - [ ] Fetch old messages (the same API, but with `?before=(messageID)` specified) when you scroll to the top. This is *not* something you can skip. See #31 for info.
  - Messages are displayed in groups. These follow PullJosh's design. (You can use placeholder profile pictures for now.) Group timestamps should be formatted according to https://github.com/towerofnix/decent/issues/116#issuecomment-352268366. To determine if a message should appear in the same message group as another, the following conditions should be true:
    - The two messages should have the same author (ID).
    - The two messages should be consecutive. Message A shouldn't appear in the same group as Message C if Message B is already in a different group (e.g. because it has a different author).
    - The message group should never contain more than 20 messages.
    - If the later message was posted at least an hour after the earlier one, it shouldn't be in the same group.
- [x] Store and load session data (and the added server list) from `localStorage`. See #113. When you sign in, you should stay signed in until you click the "log out" button, even if you reload the page.

I'm picking all of the above things for two reasons, generally. The first is that it'll get things done - several of those have never been implemented before. The second, more important one, is that it'll show the strengths of using one framework - really, one client's code - over the other. These are fairly complicated and varied tasks (generate message groups and load them on scrollback, handle logged in/out state, interact with the API).

Have fun and *please* do ask me about anything related in comments/on matrix (ideally here; if on matrix, ping me).

**Comment by PullJosh** [comment]
This is awesome. :tada:

**Comment by TheInitializer** [comment]
>You can't replace the existing client with a plugin for weechat, sorry. :)

:(

Can I still pretend I'm competing? What if my client's significantly better than pulljosh's or alex's?

**Comment by TheInitializer** [comment]
What if WeeChat is my web browser? 🤔

**Comment by towerofnix** [comment]
>Can I still pretend I'm competing?

Go ahead! This is still a good, maybe fun checklist to use as a base for a client, even if it's not a web-based one :)

>What if WeeChat is my web browser? :thinking:

It's not the vast majority of the world's. ![NYAN](https://user-images.githubusercontent.com/9948030/34169849-ab3a6bdc-e4e0-11e7-9e84-9b5d9926069c.gif)

**Comment by heyitsmeuralex** [comment]
![image](https://user-images.githubusercontent.com/9429556/34184471-d88cb158-e517-11e7-8bc4-8ba303cdd54d.png)

<h6>i win</h6>

**Comment by PullJosh** [comment]
I surrender. :white_flag:

**Comment by towerofnix** [comment]
@PullJosh :white_flag:

Thanks for the input on everything, and for the effort! :tada:

@heyitsmeuralex I'm reviewing your PR now (I have been all day, between school).

**Comment by heyitsmeuralex** [comment]
holy
