### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/decent#143]
### This is a meta _suggestion_. Please give feedback!

We should use start using semver at some point soon and start publishing releases. Oh, and we should move the API docs from the wiki to some folder -- `docs/` (gh-pages!) -- within this repo.

We can force all PRs to come with documentation, if the backend changed. From that we can determine whether the change is breaking, minor, or patch. This is great - custom clients can say "we support v0.2.x servers," etc.

Alongside that can go a version bump in package.json. This version should be returned at `/api/` for obvious reasons (`require('package.json').version`)

### GH Projects

What would be great would be if we used the Github Projects feature to sort what needs to be in which release. This would mean we'd develop in major/minor version branches - for example `v0.4` - and create PRs _into_ that branch from feature branches. Then, after everything needed is merged into `v0.4` we can perform another review where everyone checks that it's stable :shipit: Then, _that_ can be merged into master.

That probably made zero sense, so here's a diagram :package:

![image](https://user-images.githubusercontent.com/9429556/34342699-b5e72cd6-e9af-11e7-92a3-2482fef1100a.png)

Notice that work on v0.4 started before v0.3 was merged into master (very possible under this system) and also that no work (other than package.json.version updates, for example) is made on version branches without a sub-branch first, just like master currently.

We'd also use Github releases whenever anything is merged into master, as it's a new release. Alongside the release would be the source and docs (possibly in HTML form) for people to use. This would be very helpful for people implementing clients for older, un-updated servers, as they can quickly jump to the docs for v0.8.4 whilst the latest is v1.0.2, as the gh-pages docs will only show 1.0.2 and not the older version's docs.

**Comment by heyitsmeuralex** [comment]
This will also _make_ us do what needs to be done but nobody actually wants to do - like scrollback was.

We'd schedule the feature for v0.6, two mj version in the future, and we _will not_ release (merge-into-master) v0.6.0 until it's been done :tada:

**Comment by heyitsmeuralex** [comment]
Would be nice to create CONTRIBUTING.md file to detail this, assuming we begin doing it 💯

**Comment by PullJosh** [comment]
This all sounds good. :+1:

**Comment by heyitsmeuralex** [comment]
@towerofnix:

![image](https://user-images.githubusercontent.com/9429556/34361599-5f17b182-ea63-11e7-9441-48f001a7c616.png)

**Comment by heyitsmeuralex** [comment]
As-per discussion I've added issues to [Projects](https://github.com/towerofnix/decent/projects) for minor versions up to 1.3.0. Soon as we complete everything slated for 1.0.0 we should release it and begin adhering to semver :tada:

**Comment by heyitsmeuralex** [comment]
Actually, I've changed my mind on this.

Until we get to a point where Decent is used in the Real World ™️ we don't really need to do releases - so let's wait for that time 😉
