### ISSUE TITLE
Public Decent server for discussion of the project

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/decent#144]
Many other projects do this, and ours would be _meta_.

Would be nice (esp. for other, future contributors) for us to stop using the matrix Decent room and instead have a server up dedicated to Decent discussion, both dev and otherwise.

e.g.

> From [the chat](#):
> > alex: interesting point
> > PullJosh: hmm
> > florrie: solution
>
> That needs to be taken into account when fixing this.

This kind of context would really help, especially for other contributors/viewers who may not have a way to view the matrix chat.

Question is: ...hostname?

**Comment by PullJosh** [comment]
hmm

**Comment by towerofnix** [comment]
`decent.imalex.xyz` 🤷

**Comment by PullJosh** [comment]
I've considered contacting the owner of `decent.chat` to see if they'd be willing to sell for cheap (like <$20 cheap). If so, `meta.decent.chat` would be fun. :P

**Comment by heyitsmeuralex** [comment]
do it

**Comment by heyitsmeuralex** [comment]
Update: the lovely @jamesyoung has given us http://decent.chat ❤️  Going to spawn a server on a subdomain there now.

**Comment by 109C** [comment]
@heyitsmeuralex decent.chat has SSL problems.

**Comment by heyitsmeuralex** [comment]
Indeed it does - https://decent.chat isn't actually handled anywhere by my server so it's trying to respond with a 301 redirect to https://nonfree.news, which it can't do since there's no cert for decent.chat.

meta.decent.chat exists, though. Albeit the webapp is kinda broken from what I can tell :shipit:
