### ISSUE TITLE
Prompt modals should have their inputs disabled while validating

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#57]
When registering on @heyitsmeuralex's testing server, I typed out the name `florrie`. I pressed enter, to select that as my username. Nothing appeared to happen for about half a second, and I'd already started typing the password I wanted to use. By the time the prompt finished verifying and the password box opened, I'd already entered two of the characters in my password - `ab`, for example. So it wasn't obvious to me if, once I confirmed the register (i.e. entered a password), my username would be `florrieab` or `florrie`. So I canceled the register. This confusion seems unnecessary. (Also, if it would be `florrieab`, and florrieab *was* taken, I wouldn't know, since the verification checked `florrie`!)

While verifying, in general, inputs should not be changeable. When an input is being verified, a snapshot of the value is taken, which is passed to the server; so, if the user changes that value on their end *after* the verification request is sent, the server will respond based on the value originally passed to it, which could lead to errors such as the given username not being available. And, of course, if the user expects the next prompt to instantly appear, they'll start typing; that's what leads to the input's value being changed after pressing enter in the first place.

Related to #34 - this should probably be done first/separately, though, so that there's still a two-part prompt to work on.

**Comment by towerofnix** [comment]
Reopening since this isn't fixed in the new client.

**Comment by heyitsmeuralex** [comment]
This _is_ fixed in the new client.
