### ISSUE TITLE
Visual indicator of message being edited

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/decent#58]
Perhaps lower the opacity of the message currently being edited. The "Send" button should also be changed to say "Edit" (and perhaps a "Cancel Edit" button should appear beside it).

**Comment by heyitsmeuralex** [comment]
There's a class that gets added to messages when they're being edited already - we just need to use it.

**Comment by heyitsmeuralex** [comment]
@PullJosh I'd reckon you might want to do this, since you have a good pair of design goggles 👀

**Comment by towerofnix** [comment]
Closing in favor of #115.
