### ISSUE TITLE
Server settings pane UI

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/decent#67]
Literally just UI - all we need is a way to switch pages to an admin-only server settings pane

###### Ping @PullJosh: I can do the implementation of this, just have some pretty icon or whatever for me to work with thanks <3

**Comment by heyitsmeuralex** [comment]
[@PullJosh's mockup](https://codepen.io/PullJosh/pen/OOYZWK) includes a section in the sidebar for server settings:
![image](https://user-images.githubusercontent.com/9429556/33723205-f0c3745e-db63-11e7-8e6f-a71fae67969e.png)
Clicking on one of these would, I assume, load up a settings window in the central pane (where messages live). This should be reasonably simple to implement.

**Comment by towerofnix** [comment]
@heyitsmeuralex Comments on what should actually be included in the server settings pane? I can only think of the server name (and maybe the default channel layout settings, as per #66).

**Comment by heyitsmeuralex** [comment]
Emoji.

**Comment by towerofnix** [comment]
Yup - when #18 is implemented. For now, not needed (to be designed or implemented).

**Comment by heyitsmeuralex** [comment]
Most of the general settings-related UI was done in #129, albeit for _account_ settings, not server-wide ones.
